### ISSUE TITLE
Search engine in and outside

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#13]
Search in admin panel and frontend will be very useful and good for SEO

**Comment by Awilum** [comment]
What exactly do you mean?

**Comment by koreos** [comment]
Just search in content like this https://github.com/search
Also search files in admin panel.

**Comment by Awilum** [comment]
thanks, I will think about it! First I need release a first version of Admin Panel!

**Comment by koreos** [comment]
In Monstra you suggested use Google Search but I think it isn't good idea, GS use ads..
Yes, of course, Admin Panel is very needed we can not wait :-)
I tested most CMS of the world and I have to say that Monstra Admin Panel is really the best! Is very simple, very useful, very nice, very transparent and responsive of course!

**Comment by Awilum** [comment]
Not relevant to Flextype Core. This task sounds like plugin request
