### ISSUE TITLE
Local Server ERRORs

### ISSUE THREAD

**Issue by niodis** [flextype/flextype#132]
Hello!
After installing on a local server ( Laragon and OpenServer ) everything seems to be OK, but when trying to create an Entry, the  entry type option is unavailable, and after clicking on "Create" button, Flextype gave an ERROR.
But on a real server everything is working normally without any errors.
I have already checked php modules and htaccess file..
I would realy like to work with FlexType on the local server, could you please give some hint?
Thanks in advance!

**Comment by Awilum** [comment]
please check 
http://flextype.org/en/documentation/guide/basics/requirements
http://flextype.org/en/documentation/guide/basics/installation
