### ISSUE TITLE
Snippets and Blocks like in Monstra

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#14]
Please do snippets and blocks at least good like in Monstra or better.
It is very simple to use in content and php files even for people are not webmasters!

Please do Flextype for people, not only for webmasters.

**Comment by Awilum** [comment]
> Please do Flextype for people, not only for webmasters.
It is a very good point :) Need to find a balance :)

**Comment by koreos** [comment]
Sergey, you are very good programmer! 

Problem is that you stopped update Monstra...

**Comment by Awilum** [comment]
Done
