### ISSUE TITLE
После обновления на Flextype 0.4.3  - Internal Server Error 500

### ISSUE THREAD

**Issue by FullZero5** [flextype/flextype#18]
Развернул **Flextype 0.4.3** 

1. - Скопировал каталог  home
2. - Переименовал в test
3. - При переходе http://адрес_сайта/test

> Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

**Comment by Awilum** [comment]
Flextype 0.4.3 - скаченная сама по себе работает ?

**Comment by FullZero5** [comment]
И так и так, скачал (на чистую азвернуд) добавляю страницы мимо

**Comment by Awilum** [comment]
скорее всего это проблема с конфигурацией сервера 
в гугле по запросу: _Internal Server Error The server encountered an internal error or misconfiguration and was unable to complete your request._
нахожу много подобной ошибки у разных пользователей для разных систем

**Comment by FullZero5** [comment]
Не знаю, просто проект развернут на с9.io (слежу за развитием проекта, жду админку :) ) С выходом каждой новой версии скачиваю и разворачиваю на сервере, вышла новая все удалил залил из архива  потом -> composer install, начал добавлять страницы и все 500 ошибка 404 страница тоже не показывается :(
хотя если в настройках /site/config/site.yaml указывать
 pages:
  main: test 
все хорошо страница отображается

**Comment by Awilum** [comment]
Кстати вышла Flextype 0.4.4 - https://github.com/flextype/flextype/releases/tag/v0.4.4

**Comment by FullZero5** [comment]
Спасибо я увидел в ленте в ней та же проблема, - решил вообщем так изменил .htaccess


RewriteEngine on

# hide files and folders
RedirectMatch 404 /\.git
RedirectMatch 404 /composer\.
RedirectMatch 404 /.bowerrc

# If a directory or a file exists, use the request directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# Otherwise forward the request to index.php

RewriteRule . index.php

**Comment by Awilum** [comment]
как по мне это какая та специфичная проблема проблема на с9.io
на локальном севере и на серевере time web где хостится офф. сайт проекта, такую проблему воспроизвести не могу.

**Comment by FullZero5** [comment]
Вообщем для тех у кого https нужно просто добавить в .htaccess две строчки
RewriteCond %{HTTP:X-Forwarded-Proto} https
RewriteRule .* - [E=HTTPS:on]
