### ISSUE TITLE
Moving to Slim4

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#199]
Moving to Slim4 https://github.com/slimphp/Slim/pull/2769

**Comment by Awilum** [comment]
skeletons to review 
1. https://github.com/semhoun/slim-skeleton-mvc
2. https://odan.github.io/slim4-skeleton/

**Comment by exts** [comment]
Do you need help with this? I haven't touched slim in a while, but I am interested enough to maybe give it a try and contribute to open source.

**Comment by contactjavas** [comment]
Moving to Slim 4 would be great!

**Comment by Awilum** [comment]
Flextype successfully migrated to Slim4!
Branch `199-feature-moving-to-Slim4` successfully merged with `dev` branch. Further updates and fixes will be in the `dev` branch, especially for plugins. Plugins need to be retested and updated for Slim4.
