### ISSUE TITLE
Flextype Admin Panel: Moving to Tailwind CSS

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#211]
Moving to Tailwind CSS. Removing Twitter Bootstrap

**Comment by proweb** [comment]
why Tailwind and not [UIkit3](https://getuikit.com) for example?

**Comment by Awilum** [comment]
@proweb need to think about this. For me it is the same Twitter Bootstrap but from other dev's and named UI Kit. 

Tailwind is a totally different approach, that can speed up frontend twice!
As I see Tailwind used by GitHub, Heroku, Kickstarter, Twitch, Segment, Algolia.

Interesting article by Sarah Dayan
https://blog.algolia.com/redesigning-our-docs-part-4-building-a-scalable-css-architecture/

> We’ve had great success with going utility-first in the Algolia documentation, reducing our CSS from over 125 KB (and continuously growing) to less than 50 KB (9 KB GZipped, 7 KB with Brotli compression), which represents a 60% size decrease! From a user perspective, this is a guarantee of lightning-fast loading styles with extremely low overhead.

**Comment by Awilum** [comment]
need more time to investigate this question

**Comment by proweb** [comment]
Well it's more taste choice. UIkit3 also component based CSS framework, created by germany team [Yootheme](https://yootheme.com/about) and used them in workflow. 

Layout examples:

- https://zzseba78.github.io/Kick-Off/
- https://github.com/chekromul/uikit-ecommerce-template

**Comment by Awilum** [comment]
another interesting article from Adam: https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

**Comment by NuarkNoir** [comment]
> GitHub
GutHub uses Primer. How about it? https://primer.style/

**Comment by Awilum** [comment]
Any way we should not use super heavy Twitter Bootstrap (even with PurgeCSS) - at lease for client part. I will review different solutions. Thanks for all yours feedback.

**Comment by Wulfheart** [comment]
Tailwind CSS is also quite heavy. However there are literally tons of unused classed so PurgeCSS should be sufficient. Furthermore the stylesheet can also be compressed.

@oliver-77 Bulma is a great framework if you want to make a really, really quick website prototype but lacks flexibility in many ways. 
I'm convinced that Tailwind is capable of becoming the new Bootstrap in terms of adoption.

**Comment by Awilum** [comment]
Task #211 already done on 90% and it will be released in 0.9.7.

Branch: **211_moving_admin_panel_to_tailwind_css_** will be merged into dev and closed.
Development for this task will be continued in the **dev** branch.

**Comment by Awilum** [comment]
Done in 0.9.7.
