### ISSUE TITLE
How do I make links to pages?

### ISSUE THREAD

**Issue by mrjovanovic** [flextype/flextype#22]
I apologize for this stupid question, but I simply don't understand what I'm doing wrong. I believe I am following the documentation properly.

I have the following pages:
* `/var/www/html/site/pages/home/page.md`
* `/var/www/html/site/pages/cv/page.md`

all files and directories are owned by www-data. cache is off.

`../home/page.md` contains `[link](/cv)`, but following the link gives a 404 error. 

Running nginx on debian stable.

**Comment by Awilum** [comment]
by default Flextype goes with apache config and didn't tested on nginx. Did you create a configuration file for your nginx server as we do for apache ? https://github.com/flextype/flextype/blob/master/.htaccess

**Comment by mrjovanovic** [comment]
Thanks for the response, I've tried some debugging, and now firefox opens the php files as BIN (attempting to save them), while qutebrowser just gives a 404. I have this in my nginx config:
```
server {
        server_name server.net www.server.net;
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        ssl_certificate /etc/letsencrypt/live/server.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/server.net/privkey.pem;

        root /var/www/html;
        index index.php index.html index.htm index.nginx-debian.html;

# first try to serve request as directory, then file, then php, then 404
        location / {
                try_files $uri $uri/ /index.php?$args =404;
        }

# pass PHP scripts to FastCGI server 
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.1-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
        }

# deny access to .htaccess files, if Apache's document root
# concurs with nginx's one
#
        location ~ /\.ht {
                deny all;
        }
}
```

**Comment by mrjovanovic** [comment]
Working config (after clearing browser cache):

```
location ~ /(\.htaccess|\.git|flextype|vendor|CHANGELOG\.md|LICENSE\.txt|composer\.(json|lock)) {
                return 404;
        }    

location / {
                try_files $uri $uri/ /index.php?$uri&$args;
        } 

# pass PHP scripts to FastCGI server
location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php7.1-fpm.sock;
        }             
       
```
Idea for docs improvement - add nginx section. What helped me debug was the [pico cms nginx docs](http://picocms.org/in-depth/nginx/).

**Comment by Awilum** [comment]
@mrjovanovic issue is fixed ?

**Comment by mrjovanovic** [comment]
Yes, sorry, thought I closed it.
