### ISSUE TITLE
Not found pages with status code 200

### ISSUE THREAD

**Issue by alexantr** [flextype/flextype#26]
App must return 404 status code for not found pages. It is 200 now.

Tested on version 0.5.0 with php 7.2 on Win 10.

Your site have same bug:

![Status 200](https://user-images.githubusercontent.com/4941848/41273661-0bfac086-6e23-11e8-9d69-1d82650377b6.png)

**Comment by alexantr** [comment]
Bug presents in 0.6.0 version too

**Comment by Awilum** [comment]
Thanks @alexantr
