### ISSUE TITLE
`Please run: composer install` message in browser

### ISSUE THREAD

**Issue by Wulfheart** [flextype/flextype#273]
After installing via composer according to the [docs](http://docs.flextype.org/en/basics/installation) I get the following message in my browser: `Please run: composer install`
Rerunning `composer install` in the flextype folder results in 
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../doctrine/coding-standard/lib,../../slevomat/coding-standard
```

Any ideas how to fix this?

**Comment by Awilum** [comment]
Hello @Wulfheart 
please check updated version of the doc http://docs.flextype.org/en/basics/installation

**Comment by Wulfheart** [comment]
Thanks for your quick response.
Please note that the readme should also be updated accordingly.
