### ISSUE TITLE
Admin panel - Layout / Field options

### ISSUE THREAD

**Issue by AndiLeni** [flextype/flextype#29]
I have several questions and improvment ideas for the admin panel which I would like to share.
I don't know wether you know Kirby cms (www.getkirby.com), but they have some good functions for users to use own fields and create own sections. 

The first and most usefull (in my opinion) is the fields option to create a layout with specific content for each template. Kirby uses a .yaml file to define content. 
For example:  (https://getkirby.com/docs/panel/blueprints/form-fields)
````
fields:
    text:
        label: Text
        type: textarea
        required: true
````
creates a textfield where the content can be accessed from the template.

Another great idea are structured fields. They can be used to create several items with the same structure (for example team members).
See: https://getkirby.com/docs/cookbook/structured-field-content

My last question is about the file syntax Flextype uses to store all the information. Due to the fact that it does not use a database a flexible storing mechanism would be prefarable.
Could you provide an example of a saved file?

**Comment by Awilum** [comment]
Hello @AndiLeni 
Thanks you for your input. I will check this links.
Admin plugin is not ready yet, and a lot of things will be improved and changed in the admin plugin but Flextype is already ready for site development! 

Let me try to explain about data storing for Flextype. There is basically two possible way of storing data. 

1. Pages
Pages are the fundamental building-blocks of your site. Each page in Flextype should contains page header block in YAML format at the top of the file and page content marked up using HTML + Shortcodes at the bottom of the file.

Here is a basic example:
```
---
title: My Page
description: My page description
---
My page content.
```

Between these triple-dashed lines, you can set predefined page header variables or even create custom ones of your own. These variables will then be available to you to access in site templates.

2. Any Other Custom Plugin  
You should save your data with help of [YAML Files](https://symfony.com/doc/current/components/yaml/yaml_format.html#content_wrapper) using already build in [YAML component](https://symfony.com/doc/current/components/yaml.html#content_wrapper) in **/site/data/your-plugin/** dir.

**Comment by pascoal-sistemas** [comment]
Already in September and no admin panel!

This project without admin is somewhat ridiculous !!

The differential would be a panel to manage every site and post, no panel becomes bad !!

Who will use this system ??? At the moment we have 1000x better web systems!

The most important is the panel !!!!!!!!!!!!!

Without panel this project becomes a crap with no logic of use !!

**Comment by Awilum** [comment]
moved to https://github.com/flextype-plugins/admin/issues/80
