### ISSUE TITLE
Admin plugin

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#3]
Create admin plugin to manage
- Pages
- Plugins
- Users
- Settings

**Comment by koreos** [comment]
Admin panel is very needed. Also to manage snippet. Admin interface like in Monstra was very good.

**Comment by koreos** [comment]
Please also add to admin/core: News system and Blog system - today most people want to need on website: Pages, Blog and News.

**Comment by Awilum** [comment]
@koreos yes, admin plugin is high priority and should we done, but for near future there is several things also with high priority and must be done:
- improve core architecture, made it strong for Flextype 1.0 release
- create a lot of useful plugins that will be helpful for site development
- create few themes
- create strong documentation and community.

**Comment by koreos** [comment]
@Awilum Thanks for answer, but for Users admin panel is really needed now. I'm a user not webmaster and I installed Flextype but I can't use it without admin panel - it takes too much time. Admin panel in Monstra is perfect - very nice, very helpful and useful and responsive!

Important question: Is it possible to use Flextype for big project with for example 500 000 simple pages/subpages with some text, one picture and Disqus comment on every page? It will be works good and fast?

**Comment by Awilum** [comment]
@koreos I understand you. And agree about Admin panel is very important. I will start develop it in April  . No estimates, but I hope to release it until and of April. Currently I am developing site for Photographer with Flextype (without admin panel) - it is super easy and so simple :) 

**About using Flextype in the big projects.**
I don't have any numbers yet about speed, but!
Flextype is much and much faster than Monstra for big projects! 
Also Flextype uses Doctrine cache! and it allows to cache any data any where.

**Comment by koreos** [comment]
Ok I understand thank you for full answer :-)

**Comment by Awilum** [comment]
Issue closed - not actual for this repo
