### ISSUE TITLE
TinyMCE

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#31]
Yes, thank you for 0.7 with admin! Please add Tiny MCE editor as a plugin.

**Comment by Awilum** [comment]
Admin plugin will be improved step by step :)

**Comment by Awilum** [comment]
@koreos please add all your comments about admin plugin here: 
https://github.com/flextype-plugins/admin

**Comment by Awilum** [comment]
Another ticket created - https://github.com/flextype-plugins/admin/issues/4
