### ISSUE TITLE
Error404 when add plugins

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#32]
There is an error404 when we add plugins to the directory /site/plugins

**Comment by Awilum** [comment]
what version ?

**Comment by koreos** [comment]
0.7.0 of Flextype and Plugins from here https://github.com/flextype/plugins/issues

**Comment by Awilum** [comment]
Yes, I will fix them all for Flextype 0.7.0

**Comment by koreos** [comment]
Ok, thank you, I hope not for a few months.. :-)
