### ISSUE TITLE
Login page height jumping

### ISSUE THREAD

**Issue by igoryen** [flextype/flextype#354]
**Describe the bug**
Browser: Chrome.
Device: Desktop.
Page: Login.
When you navigate to the login page (New or Old user), the height of the page is rapidly changing. This causes
1) the vertical scrollbar to appear and disappear every second.
2) The input fields shrink and expand by a little with the same frequency.

**To Reproduce**
1. Go to `https://flextype.org/en/downloads`
2. Download the archive version `0.9.6`
3. Install flextype locally
4. Go to Admin page
5. Observe the jumping

The same goes for the `/admin/login` page.

This behavior doesn't happen on mobile (checked in the Chrome emulator).

**Expected behavior**
Steady page.

**Screenshots**
![200109-flextype-login-height-jump](https://user-images.githubusercontent.com/3900509/72084570-bc7bb900-32d1-11ea-97dc-274165e50a34.gif)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome.
 - Version: `79.0.3945.88 (Official Build) (64-bit)`

**Smartphone (please complete the following information):**
not tested

**Additional context**
n/a

**Comment by Awilum** [comment]
can't reproduce in 0.9.7.
