### ISSUE TITLE
Assets are referenced with basic auth credentials – getting blocked by chrome/chromium

### ISSUE THREAD

**Issue by misterunknown** [flextype/flextype#357]
**Describe the bug**
Flextypes assets are referenced with an url that contains possible basic auth credentials. These requests are blocked by chrome and chromium, but imo that is a security problem, too.

**To Reproduce**
1. Install fresh flextype
2. Enable basic auth (either .htaccess or vhost)
3. Open site in chrome or chromium
4. See that neither the css nor the js assets are loaded

**Expected behavior**
The URLs to the assets shouldn't and imo mustn't contain any credentials. I wasn't able to track down the responsible code.

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/3264829/72431113-550fae80-3794-11ea-856d-a2c4ad5a9fec.png)
![Screenshot 2](https://user-images.githubusercontent.com/3264829/72431446-280fcb80-3795-11ea-9445-e1033ba021eb.png)

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser: Chrome/Chromium, all current versions

**Comment by Awilum** [comment]
Hello @misterunknown 

try to update this code in https://github.com/flextype/flextype/blob/211_moving_admin_panel_to_tailwind_css/site/themes/default/templates/partials/base.html

from:
```
{% set build_css = '/site/themes/' ~ registry.settings.theme ~ '/assets/dist/css/build.min.css' %}
```

to: 
```
{% set build_css = '/site/themes/' ~ registry.settings.theme ~ '/assets/dist/css/build.min.css' %}
```

will it resolve your issue ?

**Comment by misterunknown** [comment]
Not really. It resolves the issue if flextype is located in the DocumentRoot, but not if it's placed in a subdirectory, like in my webserver.

**Comment by Awilum** [comment]
related ticket: #373

**Comment by Awilum** [comment]
New: 
- add new twig function {{ site_url() }}
- add new shortcode [site_url]
