### ISSUE TITLE
[PLUGIN/CORE] Blog and News

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#40]
Add Blog and News system.

**Comment by Awilum** [comment]
@Bot-Mr-Tomtastic you have troubles with installation ?
please check this page http://flextype.org/documentation/basics/installation

**Comment by Awilum** [comment]
@Bot-Mr-Tomtastic  also http://flextype.org/documentation/basics/requirements

**Comment by Awilum** [comment]
@Bot-Mr-Tomtastic if you will go to http://flextype.org you will see a Landing page that will describe Flextype
