### ISSUE TITLE
[Plugin/Core] Hooks with rules 

### ISSUE THREAD

**Issue by koreos** [flextype/flextype#41]
Hooks are very important today. 
Also with rules on specific pages don't want to show something. 
Here is very good example https://docs.generatepress.com/article/hooks-element-overview/

**Comment by Awilum** [comment]
Hooks already implemented in Flextype as it was in Monstra 
You propose to create a plugin for create some new hooks via Admin Panel Interface ?

**Comment by koreos** [comment]
Oh, I didn't know.. How it works now in Flextype?
Very important is rules because sometimes you don't need/want to display hook on specyfic page - for example: adsense code on 404 page.
