### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by puuble** [flextype/flextype#415]
i followed all instruction for install but i cant run on my local. Just see White page no error nothing attempt any alert. Pls help me

**Comment by Awilum** [comment]
1. Did you download Flextype package from this page: https://flextype.org/en/downloads ?
2. Did you check your system requirements: https://docs.flextype.org/en/basics/requirements ?
3. Did you check Installation issues section: https://docs.flextype.org/en/basics/installation#installation-issues ?

**Comment by puuble** [comment]
section 1 checked is done

> * Did you download Flextype package from this page: https://flextype.org/en/downloads ?
DONE
> * Did you check your system requirements: https://docs.flextype.org/en/basics/requirements ?
DONE
> * Did you check Installation issues section: https://docs.flextype.org/en/basics/installation#installation-issues ?
DONE 
AND again white screen nothing attempt error or anything. I will try five diff custom server and the result is the same. it shouldn't be that hard. nevermind I research another script I will not get tired in the installation.

**Comment by Awilum** [comment]
check you server error logs

**Comment by Tekl** [comment]
I had the same problem with a local MAMP server. I had to disable APC caching in the PHP settings.
