### ISSUE TITLE
lists, tables, links, hr : invisible in the editor

### ISSUE THREAD

**Issue by alextavu** [flextype/flextype#418]
in plugin/admin/assets/dist/css/admin-panel-build.min.css

add : 

.trumbowyg ol,ul{list-style-type:initial;}

.trumbowyg .table>tbody>tr>td,.table>tbody>tr>th{border-color:grey;border: 1px solid grey;padding: 1em}

.trumbowyg a{color:blue;}

.trumbowyg  hr{border:none;height:1px;color:black;background-color:black}

**Comment by Awilum** [comment]
moved to https://github.com/flextype-plugins/form/issues/2
