### ISSUE TITLE
Template creating error: Slim Application Error

### ISSUE THREAD

**Issue by emmarvpol** [flextype/flextype#422]
Hello, when Im trying to create a new template Im getting this error:

Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

Updated: When Im go back its  works

**Comment by Awilum** [comment]
Hello @emmarvpol 

There is an issue with wrong redirect after new template creation. 
This issue will fixed in next release

**Comment by emmarvpol** [comment]
Ok! Thanks you!

**Comment by Awilum** [comment]
Fixed
