### ISSUE TITLE
Орфографическая ошибка при первой установке

### ISSUE THREAD

**Issue by smell-of-rain** [flextype/flextype#425]
![2020-04-28_230701](https://user-images.githubusercontent.com/45331093/80523236-6755d700-8996-11ea-82f2-c098cc2841bb.jpg)
правильно будет successfully, я только что её установил, на бесплатном хостинге, хотел опробовать, но страница admin не найдена.
Наверное я что-то неправильно сделал.

**Comment by Awilum** [comment]
http://docs.flextype.org/en/basics/requirements
http://docs.flextype.org/en/basics/installation

**Comment by Awilum** [comment]
not relevant anymore
