### ISSUE TITLE
Broken link in README.MD

### ISSUE THREAD

**Issue by badcat** [flextype/flextype#426]
Broken link in README.MD
https://flextype.org/en/api-token-generator

Also main links in 404 page also broken.

**Comment by KoljaL** [comment]
still broken :-(

**Comment by Awilum** [comment]
This link related to upcoming 0.9.8 release.
api-token-generator link will be fixed with 0.9.8 release

release should be in mid-end of May

**Comment by Awilum** [comment]
fixed
