### ISSUE TITLE
Old Website Doc

### ISSUE THREAD

**Issue by agl-developer** [flextype/flextype#427]
I noticed that with the new update the old documentation is no longer available. The updated site lacks a lot of the old docs.

I know you are working hard in flextype and appreciate the work, but is there a way to access the old docs?

**Comment by Awilum** [comment]
Hello!

I will fix it during today-tomorrow.
Old docs will be available by url http://docs.flextype.org/0.9.7/

**Comment by Awilum** [comment]
added

http://docs.flextype.org/en
http://docs.flextype.org/0.9.7/en

**Comment by agl-developer** [comment]
Thank you so much! And great job with flextype in CMS.
