### ISSUE TITLE
Typo on class name causing errors on 0.9.11 release zip

### ISSUE THREAD

**Issue by btalanski** [flextype/flextype#483]
There is currently a typo on the class name for the APCU cache adapter which causes the application to fail.

**To Reproduce**
When the application is loading the APCU cache adapter on `dependencies.php` the driver name has the correct string. When looking for the adapter class to load, it will try to load `"Flextype\App\Foundation\Cache\ApcuCacheAdapter"`.

The class does not exist, as the file name and exported class name have typos:
`"Flextype\App\Foundation\Cache\ApcuCacheAdapter"` and `class AcpuCacheAdapter implements CacheAdapterInterface`

**Expected behavior**
Application should be able to load the appropriate cache adapter for APCU cache.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/26017611/99886496-4e9f5e00-2c13-11eb-8d5f-b86e82a4e423.png)
![imagem](https://user-images.githubusercontent.com/26017611/99886501-5828c600-2c13-11eb-8858-5d109e5f64ce.png)

**Comment by Awilum** [comment]
@btalanski this is know issue and will be not actual in upcoming 0.9.12, because we will use PHPFastCache https://github.com/flextype/flextype/issues/457 

for now you may use any other PHP Driver, by updating this setting here 
https://github.com/flextype/docs.flextype.org/blob/master/project/config/flextype/settings.yaml#L117 

```
    $drivers_classes = [
        'apcu' => 'Apcu',
        'wincache' => 'WinCache',
        'phpfile' => 'PhpFile',
        'phparrayfile' => 'PhpArrayFile',
        'array' => 'Array',
        'filesystem' => 'Filesystem',
        'memcached' => 'Memcached',
        'redis' => 'Redis',
        'sqlite3' => 'SQLite3',
        'zenddatacache' => 'ZendDataCache',
    ];
```

**Comment by Awilum** [comment]
not relevant for upcoming 0.9.12 release. closing
