### ISSUE TITLE
Flextype website: wrong dates on changelog (0.9.16 & 0.9.15)

### ISSUE THREAD

**Issue by FBachofner** [flextype/flextype#542]
On the website. the [changelog](https://flextype.org/en/changelog) shows incorrect dates for 0.9.16 & 0.9.15

It shows them as having been updated in 2020 (instead of 2021).

Since earlier changes are "below the fold" this may make newcomers think flextype is not being actively updated.  I was almost discouraged myself -- and then (after scrolling down) a slight bit confused that dates seemed so out of order.

**Comment by Awilum** [comment]
@FBachofner Thanks! I will fix this ASAP

**Comment by Awilum** [comment]
Fixed

**Comment by FBachofner** [comment]
I am just astonished (and pleased) you are so responsive!  Good for you.

Going to play with Flextype this upcoming weekend!
