### ISSUE TITLE
Menu hide upside of blog edit page

### ISSUE THREAD

**Issue by iozcelik** [flextype/flextype#544]
**Describe the bug**
When open a blog post for editing, menu hide upside of page. So it is not possible to change post name and choose setting tab.

**To Reproduce**
Entities -> Blog -> One of the blog post

**Screenshots**
![image](https://user-images.githubusercontent.com/10682780/116780882-e25d3c00-aa87-11eb-9649-368e5fdc3f6f.png)

**Comment by Awilum** [comment]
will be not actual for upcoming release. closing.
