### ISSUE TITLE
Flextype Admin Panel: add RTL url support.

### ISSUE THREAD

**Issue by uwejan** [flextype/flextype#62]
Hi, I just new started with FlexType, i find it really flex in development, not with RTL url support, say i want to create a page such /blog/موضوع-جديد  which is same as /blog/new-topic , the CMS will not allow it.
The CMS is flex and growing and i think its very important if it could support RTL url's.

**Comment by uwejan** [comment]
any updates on this issue?

**Comment by Awilum** [comment]
New option added for admin panel

```
entries:
  slugify: true 
```

this option will disable slugify php and speakingurl js for entries
