### ISSUE TITLE
Unable to create new admin user

### ISSUE THREAD

**Issue by xcartmods** [flextype/flextype#76]
Hi, thought I'd give Flextype a go, but I can't create an admin user. It just says "please match the format requested". I've tried FF and Opera, with a crazy long random password. Any ideas?

**Comment by Awilum** [comment]
here is an example 

Password12345

**Comment by xcartmods** [comment]
Thank you, just needed an uppercase character.
Having tried dozens of CMS in the past, I really like the look of this :)
