### ISSUE TITLE
Admin Panel - Not responsive enough

### ISSUE THREAD

**Issue by aswzen** [flextype/flextype#94]
Hi there, 

I see the admin panel is not responsive enough, see my screenshot
![image](https://user-images.githubusercontent.com/1474916/52609403-ccb3ca00-2eaf-11e9-9622-05063bf5e5dd.png)
![image](https://user-images.githubusercontent.com/1474916/52609406-cf162400-2eaf-11e9-9060-f14dda8d31b7.png)

Please fix in next version :) thanks

**Comment by Awilum** [comment]
not related for Flextype Core
